Dirigent: seeing this error at the Github Action build for macos:
Submitti...

seeing this error at the Github Action build for macos:

Submitting for notarization...
Conducting pre-submission checks for Dirigent-notarize.zip and initiating connection to the Apple notary service...
Submission ID received
  id: 0df1452e-1bbc-4e24-80e4-9511d4426d76
Successfully uploaded file
  id: 0df1452e-1bbc-4e24-80e4-9511d4426d76
  path: /Users/runner/work/Dirigent/Dirigent/target/release/bundle/Dirigent-notarize.zip
Waiting for processing to complete.
Current status: In Progress...
Current status: In Progress....
Current status: Invalid.....Processing complete
  id: 0df1452e-1bbc-4e24-80e4-9511d4426d76
  status: Invalid
Stapling notarization ticket...
Processing: /Users/runner/work/Dirigent/Dirigent/target/release/bundle/Dirigent.app
CloudKit query for Dirigent.app (2/6faa9fdb3e9da5b4f656521ab4c110f1495689b2) failed due to "Record not found".
Could not find base64 encoded ticket in response for 2/6faa9fdb3e9da5b4f656521ab4c110f1495689b2
The staple and validate action failed! Error 65.
Error: Process completed with exit code 65.