Dirigent: Compiling Dirigent v0.3.0 (/Users/lars/prj/Dirigent) error: encou...
Compiling Dirigent v0.3.0 (/Users/lars/prj/Dirigent)
error: encountered diff marker
    --> src/git.rs:1124:1
     |
1124 | <<<<<<< HEAD
     | ^^^^^^^ between this marker and `=======` is the code that we're merging into
1125 |     Err(DirigentError::GitCommand("no main worktree found".into()))
1126 | =======
     | ------- between this marker and `>>>>>>>` is the incoming code
...
1130 | >>>>>>> deefb8521f1682e71c098d100d4a3cb75fd618a4
     | ^^^^^^^ this marker concludes the conflict region
     |
     = note: conflict markers indicate that a merge was started but could not be completed due to merge conflicts
             to resolve a conflict, keep only the code you want and then delete the lines containing conflict markers
     = help: if you're having merge conflicts after pulling new code:
             the top section is the code you already had and the bottom section is the remote code
             if you're in the middle of a rebase:
             the top section is the code being rebased onto and the bottom section is the code coming from the current commit being rebased
     = note: for an explanation on these markers from the `git` documentation:
             visit <https://git-scm.com/book/en/v2/Git-Tools-Advanced-Merging#_checking_out_conflicts>

error: could not compile `Dirigent` (bin "Dirigent" test) due to 1 previous error